### ISSUE TITLE
sudo: ./futurestore: command not found

### ISSUE THREAD

**Issue by Checkm8ra1n** [marijuanARM/futurerestore#143]
How can I fix it??? sudo: ./futurestore: command not found
![immagine](https://github.com/futurerestore/futurerestore/assets/110713827/7fef8b53-e4bd-4146-8836-1015cdeff80a)

**Comment by Cryptiiiic** [comment]
First off never run as sudo. Second terminal 101. You have a current working directory. Your current directory is `~/Desktop/downgrade/` when you type . It means you are selecting the current directory that your inside as the path to use. Since futurerestore binary isn’t inside the downgrade folder it can’t possibly do anything so put the correct path or put futurerestore in the downgrade folder.
