### ISSUE TITLE
iphone 7 (global) failed to getting firmware keys

### ISSUE THREAD

**Issue by RetroSynthwave** [marijuanARM/futurerestore#152]
Device found in DFU Mode.
Getting firmware keys for: d10ap
Cleaning up...
[exception]:
what=getting keys failed with error: 14745615 (failed to get FirmwareJson from Server). Are keys publicly available?
code=41680964
line=636
file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp
commit count=308
commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
Done: restoring failed!
[*] Done!
[*] Cleaning
[*] Done!

**Comment by Haeckli** [comment]
which IOS version did you try to restore?

**Comment by DavyA** [comment]
Same here, iPad 6th WiFi + 4G restoring iOS 16.6:

Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
Device found in DFU Mode.
Getting firmware keys for: j72bap
Cleaning up...
[exception]:
what=getting keys failed with error: 14745615 (failed to get FirmwareJson from Server). Are keys publicly available?
code=41680964
line=636
file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp
commit count=308
commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
Done: restoring failed!
FutureRestore process ended.
[66] Unable to run FutureRestore.
[67] coocoofroggy.me: nodename nor servname provided, or not known

**Comment by sevenpastzeero** [comment]
Same here. iPhone 7 Plus Global iPhone9,2. Downgrading from 15.8 to 15.7.6 using bshsh2. I had to manually set nonce using checkm8-nonce-setter, then use FR to downgrade.
A few months ago I was able to downgrade/upgrade between 14.8 and 15.4.1 multiple time using only FR, but the past couple of. days I couldn't.

Edit: I just realized that firmware keys for 15.7.6 are not available on iPhonewiki, so that is probably why. There is however keys for 15.7 (latest available ones) that I might try later to see if they work.
