### ISSUE TITLE
Can macOS-arm64-RELEASE run on linux/android arm64?

### ISSUE THREAD

**Issue by SpongebobSquamirez** [marijuanARM/futurerestore#80]
I have a rooted android, which can run things like checkra1n. I need to use futurerestore, though, and I'm afraid to use a bootable linux drive on my PC b/c I've had safemode bootloop issues in the past with it. Creating windows recovery media now just in case, but I'd rather not have to go the USB route anyway.

Does the macOS ARM64 version work on linux or other arm64 systems too? If not, could you make a build that does? Would really, REALLY help me out 😬

**Comment by Cryptiiiic** [comment]
what does macOS have to do with linux or android? they are entirely different.

**Comment by SpongebobSquamirez** [comment]
Well, mainly the fact that they're both Unix systems that accept a lot of the same commands and run a lot of the same stuff...but okay, thanks for at least confirming it's a no

**Comment by Cryptiiiic** [comment]
macOS is based of bsd not unix and the kernel is osmfk. Not only that the aarch64 processor has major hardware differences than an exclusive in-house apple designed arm chip. Linux has elf based executable format with shared object libraries. macOS has the Mach-O executable format with Mach-O dynamic libraries. So they are pretty much entirely different and not compatible whatsoever. Instead of asking for the impossible, all you have to do is build all the dependencies and futurerestore for android. I have zero experience with android so its quite the big ask of me. There is zero incentive for me to spend hours of work for 1 person who can do it themself if they put in the effort.
